### ISSUE TITLE
bob build depend relation

### ISSUE THREAD

**Issue by lewis081** [BobBuildTool/bob-tutorials#4]
Dear Author:
    Hi, I was confused with problem below.
    I get result below by typing  command `bob build  vexpress/initramfs/busybox` on example sandbox.
```
>> vexpress/initramfs/busybox
>> vexpress/sandbox::debian-8.2-x86
   CHECKOUT  skipped (fixed package work/sandbox/debian-8.2-x86/src/1/workspace)
>> vexpress/initramfs/busybox
>> vexpress/sandbox::debian-8.2-x86
   BUILD     skipped (unchanged input for work/sandbox/debian-8.2-x86/build/1/workspace)
   PACKAGE   skipped (unchanged input for work/sandbox/debian-8.2-x86/dist/1/workspace)
>> vexpress/initramfs/busybox
   CHECKOUT  skipped (fixed package work/busybox/src/1/workspace)
>> vexpress/toolchain::arm-linux-gnueabihf
   PACKAGE   skipped (unchanged input for work/toolchain/arm-linux-gnueabihf/dist/1/workspace)
>> vexpress/toolchain::x86
   PACKAGE   skipped (unchanged input for work/toolchain/x86/dist/1/workspace)
>> vexpress/initramfs/busybox/toolchain::make
   PACKAGE   skipped (unchanged input for work/toolchain/make/dist/1/workspace)
>> vexpress/initramfs/busybox
   BUILD     skipped (unchanged input for work/busybox/build/1/workspace)
   PACKAGE   skipped (unchanged input for work/busybox/dist/1/workspace)
Build result is in work/busybox/dist/1/workspace
Duration: 0:00:00.071008, 0 checkouts (0 overrides active), 0 packages built, 0 downloaded.
``` 
But i can not find the dependent tree of vexpress/initramfs/busybox.
I used command `bob ls -r` and `bob query-recipe `. But I can not find the downstream such as sandbox::debian-8.2-x86, toolchain::arm-linux-gnueabihf and  toolchain::x86.
Is there a way to know the build recipe sequence of one recipe? Read YAML file?

Thanks for your reply.

**Comment by jkloetzke** [comment]
You can list the configured dependencies of the busybox package with `bob ls vexpress/initramfs/busybox`. There you can see all direct dependencies.

What you see in the build output above is that there are further forwarded dependencies, namely vexpress/sandbox::debian-8.2-x86 (the sandbox), vexpress/toolchain::arm-linux-gnueabihf (the target toolchain) and vexpress/toolchain::x86 (the host toolchain). There is currently no switch to `bob ls` that shows you such forwarded dependencies. They are configured in vexpress and forwarded to the dependencies below that.

This forwarding only applies to tools, that is recipes that have a `provideTools`. In more complex examples you would typically see that they are "built" once at the beginning and then all packages are built with it.

**Comment by lewis081** [comment]
Thank you for your detail reply firstly.

Yeah. Actually, the real dependencies of one recipe can divide into two types. 
One is direct dependencies that show under filed of depends. the command bob ls -r <package> can show this.
Another is forwarded dependencies that show at some upstream recipes. But this dependencies need read _.yaml_ file to know.  Maybe sometime it will spend a lot of time. And it will cause confusion when the project exists lots of forward dependencies.
I think bob will be better if you add command that can show direct and forward dependencies of one recipe. We can know the dependencies of any recipe quickly.

**Comment by jkloetzke** [comment]
Yes, this should be added to Bob to be able to show the forwarded depenencies too. I've opened a ticket to track this missing feature: https://github.com/BobBuildTool/bob/issues/187.
